import type { Metadata } from "next";
import { Bricolage_Grotesque } from "next/font/google";
import { Navbar } from "@/components/Navbar";
import { ThemeProvider } from "@/components/theme-provider"
import "./globals.css";


const font = Bricolage_Grotesque({
  variable: "--font-bricolage-grotesque",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${font.className} dark:bg-[#0e1018] bg-gray-50  antialiased    `}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >

        <div className=" px-4 py-4 md:px-25 ">
          <Navbar />
          {children}
        </div>
           </ThemeProvider>
      </body>
    </html>
  );
}
